torch_args:
  nnodes: 1
  node_rank: 0
  nproc_per_node: 1
  rdzv_endpoint: 127.0.0.1:12222
  rdzv_id: 123
train_args:
  ckpt_output_dir: checkpoints
  data_output_dir: train-output
  data_path: ./taxonomy_data
  deepspeed_options:
    cpu_offload_optimizer: true
    cpu_offload_optimizer_pin_memory: false
    cpu_offload_optimizer_ratio: 1
    save_samples: null
  effective_batch_size: 100
  is_padding_free: false
  learning_rate: 2e-6
  lora:
    alpha: 32
    dropout: 0.1
    quantize_data_type: nf4
    rank: 2
    target_modules:
    - q_proj
    - k_proj
    - v_proj
    - o_proj
  max_batch_len: 1000
  max_seq_len: 96
  mock_data: false
  mock_data_len: 0
  model_path: instructlab/granite-7b-lab
  num_epochs: 1
  random_seed: 42
  save_samples: 100
  warmup_steps: 10
